version: "3"
services: 
  db: 
    image: mysql
    container_name: db
    ports: 
      - "8000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: wordpress
      MYSQL_USER: usr-wordpress
      MYSQL_PASSWORD: pwd-wordpress
  wordpress: 
    image: wordpress
    container_name: wordpress_teste
    ports:
      - "8080:80"
    depends_on:
      - "db"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress